fix: use single connection to sync all mailboxes
nextcloud/mail pull request #10117
Opened 2024-09-08 02:54 UTC by SebastianKrupinski

Resolves: #https://github.com/nextcloud/mail/issues/10098

2024-09-08 18:56 UTC, kesselb requested changes

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/ImapToDbSynchronizer.php
> +		// construct imap client and perform initial connection
```suggestion
```

https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/ImapToDbSynchronizer.php
> +		// perform mail sync on all mail boxes
```suggestion
```

https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/ImapToDbSynchronizer.php
> +		// disconnect imap client
```suggestion
```
https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/SyncService.php
> +	private $clientFactory;
```suggestion
	private IMAPClientFactory $clientFactory;
```

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/SyncService.php
> +		// construct imap client and perform initial connection
```suggestion
```

https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/SyncService.php
> +		// perform mail sync on all mail boxes
```suggestion
```

https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940

2024-09-08 18:56 UTC, kesselb commented on lib/Service/Sync/SyncService.php
> +		// disconnect imap client
```suggestion
```

https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/#h2-b7593c698a940

2024-09-08 18:56 UTC, kesselb commented on tests/Unit/Service/Sync/SyncServiceTest.php
> +	private $client;
```suggestion
	private IMAPClientFactory&MockObject $clientFactory;
	private Horde_Imap_Client_Socket&MockObject $client;
```

and import `use PHPUnit\Framework\MockObject\MockObject;`

2024-09-09 07:12 UTC, ChristophWurst requested changes

2024-09-09 07:12 UTC, ChristophWurst commented on lib/Service/Sync/ImapToDbSynchronizer.php
> +		$client->login();
This …

2024-09-09 07:12 UTC, ChristophWurst commented on lib/Service/Sync/ImapToDbSynchronizer.php
> -		$client->login(); // Need to login before fetching capabilities.
… should go back here. The login outside seems arbitrary, so the next developer might drop it.

1. Move the login back to where it matters
2. Do not drop the comment explaining why we need the explicit login

2024-09-13 05:20 UTC, ChristophWurst approved these changes

2024-09-15 15:20 UTC, st3iny approved these changes

2024-09-15 15:21 UTC, SebastianKrupinski commented
/backport to stable4.0

2024-09-15 15:21 UTC, SebastianKrupinski commented
/backport to stable3.7

2024-09-16 13:02 UTC, merged