Migrate the main mail store to Pinia
nextcloud/mail pull request #10138
Opened 2024-09-12 15:34 UTC by GVodyanov

Fix https://github.com/nextcloud/mail/issues/9237

This is going to be a big one...

Splitting stores into multiple files isn't very common in Pinia, but I really wanted to do so in this case, I took my inspiration for how to do it from these guys https://github.com/vuejs/pinia/issues/802

A little overview of how this was done:
- Created a subfolder in `/store` for all the main mail store stuff
- Migrate all the getters and remove now useless ones (the ones that just point to a piece of state without modifying it)
- Migrate the actions file
- Rename all the mutations to `[previous name]` + `Mutation` 
- Migrate `dispatch` and `commit` usages in components to the correct Pinia usage
- Move the renamed mutations into the actions file, hence making them actions (and this time I didn't inline anything, at least yet)
- Realized that a lot of the getters had parameters, which you can't have in Pinia, so those become actions as well (not renamed)
- Lots of bugfixing
- Migrate the tests (the component ones are easy, just updating references, however the ones that actually test the store itself require pretty significant modification)

2024-09-30 15:37 UTC, GVodyanov commented
Not opening the PR yet as I still have the tests to migrate, but mail is useable (as far as it seems)

2024-10-10 14:13 UTC, GVodyanov commented
Thanks so much for finishing the hardest parts Richard <3

2024-10-10 14:34 UTC, hamza221 commented
needs a rebase, I wish you luck 🍀

2024-10-10 17:47 UTC, kesselb requested changes
Should be merged after branch off for stable4.1

2024-11-20 07:59 UTC, ChristophWurst commented
Let's get this in

2025-01-07 12:09 UTC, st3iny approved these changes
Rebased, fixed conflicts and did some testing. I couldn't spot breakage.

2025-01-11 22:26 UTC, st3iny commented
No no, all good. I didn't do anything yet, just assigned myself to not forget about the PR.

Thanks for the final rebase :)

2025-01-13 09:10 UTC, merged