perf: reduce number of avatar requests
nextcloud/mail pull request #10486
Opened 2024-12-12 12:41 UTC by hamza221

2024-12-12 12:45 UTC, ChristophWurst reviewed
Quick review

2024-12-12 12:45 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +	private $UserId;
```suggestion
	/** @var string|null */
	private $userId;
```

2024-12-12 12:45 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +		string $UserId) {
```suggestion
		string $userId) {
```

https://docs.nextcloud.com/server/latest/developer_manual/basics/dependency_injection.html#predefined-core-services

2024-12-12 12:45 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +					$avatar = $this->avatarService->getAvatar($message->getFrom()->first()->getEmail(), $this->UserId);
getFrom might return an empty error. will that lead to a NPE when you call `getEmail` on null?

2024-12-12 12:48 UTC, hamza221 commented
I broke RecipientBubble 😨, turning to draft

2024-12-12 14:34 UTC, hamza221 commented
The avatar controller and frontend service are still needed for Recipient bubble (Thread.vue) , because the message object contains only from's avatar ( to, cc, bcc ) still need to be fetched , and assuming that we need them and pre-fetching is counterproductive because we can't assume that all threads are gonna be opened

2024-12-13 10:24 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +		$needAnalyze = array_reduce($messages, function (array $carry, Message $message) {
The purpose of this `array_reduce` is to find messages that need processing.

Placing the avatar logic in it is convenient but a hack. Please put this somewhere else.

I also believe that the preview enhancer is run for background job and CLI syncs. Doesn't this slow them down while the volatile avatar result is not used? Only REST calls to get the message/thread lists should have this avatar pre-fetching.

2024-12-17 08:51 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +				$from = $message->getFrom()->first() ;
```suggestion
				$from = $message->getFrom()->first();
```

2024-12-17 08:51 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +	public function process(Account $account, Mailbox $mailbox, array $messages, string $mode = 'sync'): array {
```suggestion
	public function process(Account $account, Mailbox $mailbox, array $messages, bool $preLoadAvatars = false): array {
```

2024-12-17 08:51 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +		$this->userId = $userId;
nitpick: I see injection of data as a code smell. The only exception for a valid userId injection is a controller.

Would it be possible to move the transport of the user context (userId) to the method parameters?

2024-12-17 08:55 UTC, ChristophWurst commented
How will this handle worst case scenarios? Imagine you load 20 messages and each of them is sent by someone else, and there is no contacts picture so gravatar favicon sources are tapped. These make external HTTP requests that could take several seconds, e.g. when the favicon request times out because the domain does not correspond to a HTTP server.

Will this slow down the loading of messages?

If so, we have to fine-tune the approach. Let me know, I have some ideas.

2024-12-17 14:15 UTC, hamza221 commented
So I did a little benchmarking and here are the results 

**Main**
1. /api/messages?mailboxId=1&limit=20 => 501.22 ms  
2. First batch of requests  /api/avatars/url/{email}=> 9583 ms 
total = 10084 ms 
3. external avatars (3 email addresses ) api/avatars/image/{email}  => 5158 ms

**This branch**

* /api/messages?mailboxId=1&limit=20 (combines 1 and 2 from above)   => 1.4 minutes / 2.4 minutes / 2.3 minutes 
* fetching additional messages => 16.94 seconds 

Doesn't look like a good approach 
Ps: tests done with caching disabling and no additional throttling / timeouts

2024-12-17 14:49 UTC, ChristophWurst commented
Okay, that is what I was afraid of.

Then we do it like follows: check the **cache** for an avatar URL. If it exists, attach it to the recipient. Also attach a **false** if there is one, it indicates that there is no avatar for the user.
Leave the rest of the fetching in tact.

This means that the initial loading with empty cache is still done in many requests, but those help us offload the slow fetching into async operations that don't block the main app functionality. For page reloads, mailbox switches, messages of senders seen previously etc we will preload the avatar URLs and save some requests.

2024-12-23 08:51 UTC, hamza221 commented
I'm not sure how to return state ( Avatar => avatar exists , null => avatar doesn't exist, ? => we want to fetch it from the frontend) 

https://github.com/nextcloud/mail/pull/10486/files#diff-a7e5eb4728a4ad105af312d21ceb1bd6dd7a70068ba67d4b1881099dcae1076bR99

2025-01-10 11:48 UTC, ChristophWurst commented
Avatar (value) vs `null` vs `false`? That's how we store the ternary state in the backend

2025-01-10 11:50 UTC, hamza221 commented
> Avatar (value) vs `null` vs `false`? That's how we store the ternary state in the backend

oh, it wouldn't throw an error when the return type is ?Avatar ?

2025-01-15 16:16 UTC, ChristophWurst reviewed
Code looks good!

Do you have any comparisons for nr of request after page reload from main vs this branch?

2025-01-15 16:16 UTC, ChristophWurst commented on lib/Db/Message.php
> +	 * @param bool $fetchAvatarFromClient
nit: phpdoc duplicates the native php typehint. it can go

2025-01-15 16:16 UTC, ChristophWurst commented on lib/Db/Message.php
> +	 * @return Avatar
here the typehint contradicts the native one. Is the return value nullable or not? :wink:

2025-01-15 16:16 UTC, ChristophWurst commented on lib/Db/Message.php
> +			'avatar' => $this->avatar ? $this->avatar->jsonSerialize() : null,
```suggestion
			'avatar' => $this->avatar?->jsonSerialize(),
```

https://php.watch/versions/8.0/null-safe-operator

2025-01-15 16:16 UTC, ChristophWurst commented on lib/Service/AvatarService.php
> +		if($cachedOnly){
```suggestion
		if ($cachedOnly){
```

2025-03-17 06:51 UTC, ChristophWurst commented
Mind using merges over rebases until the PR is reviewed? I can't see what you have pushed since my last review when history is rewritten.

![image](https://github.com/user-attachments/assets/d5da4a48-7bbb-4745-ae48-96285df65a00)

2025-03-17 09:18 UTC, hamza221 commented
> Mind using merges over rebases until the PR is reviewed? I can't see what you have pushed since my last review when history is rewritten.
> 
> ![image](https://private-user-images.githubusercontent.com/1374172/423343783-d5da4a48-7bbb-4745-ae48-96285df65a00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIyMDMzMDAsIm5iZiI6MTc0MjIwMzAwMCwicGF0aCI6Ii8xMzc0MTcyLzQyMzM0Mzc4My1kNWRhNGE0OC03YmJiLTQ3NDUtYWU0OC05NjI4NWRmNjVhMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTdUMDkxNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc1YTE2YjRhOWU3NDcwZGVkM2FhODdjMDM2MTg1NDEzZDBlZmQwODdjYjJjZWI3MGJkMjQwNjU0Y2Y0MzE0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.m2hSzRRgY2A0RJzTl91yLOlDfzlBejKXDIBDNHVNvZE)

I usually do, I had to rebase to resolve conflicts, and squashing made it way easier

2025-05-16 11:50 UTC, ChristophWurst approved these changes
Big :+1: 

Tested and works

Here are my numbers:
* main: takes 48 requests to load the unified inbox with three accounts
* this branch: takes 29 requests to load the unified inbox with three accounts

2025-05-16 11:50 UTC, ChristophWurst commented on lib/IMAP/PreviewEnhancer.php
> +				if ($message->getAvatar() === null && $from !== null && $from->getEmail() !== null && $userId !== null) {
nit: negate the condition and use `continue` to skip one loop iteration. That avoids at least one level of indentation in this deep indentation tree.

2025-05-16 11:51 UTC, ChristophWurst commented
@GretaD @st3iny good for you too? I guess this can be seen as part of https://github.com/nextcloud/mail/issues/10668

2025-05-16 12:42 UTC, GretaD approved these changes

2025-05-16 13:14 UTC, kesselb commented on lib/Service/AvatarService.php
> +	public function getAvatar(string $email, string $uid, bool $cachedOnly = false): mixed {
Could we add a new method getCacheAvatar instead of adding a new argument here and changing the return type to mixed?

2025-05-16 14:13 UTC, st3iny requested changes
Looks good otherwise. The amount of requests went down *significantly* on my personal mail account :rocket:

2025-05-16 14:13 UTC, st3iny commented on src/components/OutboxMessageListItem.vue
> +				::fetch-avatar="data.fetchAvatarFromClient"
```suggestion
				:fetch-avatar="data.fetchAvatarFromClient"
```

2025-05-16 14:13 UTC, st3iny commented on lib/Service/AvatarService.php
> +	public function getAvatar(string $email, string $uid, bool $cachedOnly = false): mixed {
I kind of agree with Daniel. I don't like methods returning either null or false (or an object) because it is hard to understand the semantics without knowing the method's code.

2025-06-04 17:04 UTC, hamza221 commented
added Unit tests -> codecov is now happy I'll squash, rebase and merge

2025-06-04 17:46 UTC, merged