fix(deps): Apply npm audit fix
nextcloud/mail pull request #10528
Opened 2024-12-24 03:00 UTC by nextcloud-command

Auto-generated fix of npm audit

2025-01-14 06:44 UTC, ChristophWurst requested changes
Bumps nc/vue and needs manual testing

2025-01-14 09:47 UTC, kesselb approved these changes

2025-01-14 10:16 UTC, kesselb requested changes
Sorry, approved the wrong pr :see_no_evil:

2025-05-09 11:42 UTC, ChristophWurst commented
3.7 is EOL

2025-05-09 11:42 UTC, closed without merging