Show inline avatars for all participants in a threading
nextcloud/mail pull request #3641
Opened 2020-09-23 11:33 UTC by GretaD

wip

2020-09-23 14:27 UTC, GretaD commented
@jancborchardt @ChristophWurst please have a look and let me now if all is good

2020-09-23 19:51 UTC, jancborchardt commented
Very cool! :) Bit of space between the avatar+username chips would be good – e.g. 4px. Otherwise nice!

2020-09-24 06:03 UTC, ChristophWurst requested changes

2020-09-24 06:03 UTC, ChristophWurst commented on src/components/Thread.vue
> -						<AddressList :entries="threadParticipants" />
also :fire: the address list and address components if they are now unused :)

2020-09-24 06:04 UTC, ChristophWurst requested changes
Two more things that are missing

- [ ] Clicking an avatar should redirect you to a new message to this person. Just like clicking the address did before
- [ ] There should be a way to see the email for the recipients that have a label. Can't we show that via the tooltip?

2020-09-24 14:57 UTC, ChristophWurst approved these changes

2020-09-24 15:06 UTC, merged