Fix redirect after moving thread envelope
nextcloud/mail pull request #3895
Opened 2020-10-26 10:42 UTC by st3iny

After a thread envelope has been moved the user is redirect. Currently this also happens when the user cancels the move (closes the move modal).

2020-10-27 13:08 UTC, ChristophWurst requested changes
The event names do not match – intended?

2020-10-27 16:40 UTC, st3iny commented
Yes this is intended. If return is called inside a try or catch block the finally block is run before actually returning from the function. The close event is already emitted in the finally block. The move emit is new and the removal of the close emit is just a cosmetic fix :D

The finally block:
```javascript
} finally {
	this.moving = false
	this.$emit('close')
}
```

2020-10-28 08:28 UTC, st3iny commented
Don't review yet. This is still not working as intended.

2020-10-28 11:19 UTC, st3iny commented
The responsiveness of moving envelopes inside a thread is much better now. When moving the parent envelope (currently selected in envelope list) the redirect is triggered. When another envelope from the thread is moved the view stays as is and only the thread gets refreshed.

The moved thread envelope will be collapsed but can then be extended again without any error (due to the source envelope being moved/deleted).

If the move is cancelled nothing happens.

2020-10-30 14:51 UTC, st3iny commented
Oops, I deleted my fork without moving the branch here ...

2020-10-30 14:51 UTC, closed without merging