Fix mail app accessibility
nextcloud/mail pull request #4211
Opened 2020-12-08 16:37 UTC by GretaD

Signed-off-by: GretaD <gretadoci@gmail.com>

2020-12-10 14:27 UTC, jancborchardt commented on src/components/Envelope.vue
> +			:aria-label="3">
```suggestion
			:aria-level="3">
```

Just a slight error – this needs to be level instead of label – label is the actual description. :)

2020-12-10 14:32 UTC, jancborchardt commented on src/components/Envelope.vue
> +			:aria-label="3">
Ah and these should also go into the router-link instead, to only have it once instead of 3 times.

2020-12-16 14:16 UTC, ChristophWurst commented
@GretaD could you fix the eslint issue? Then I'd say we get this in and start the next item on @yplassiard's list :)

2020-12-19 19:12 UTC, jancborchardt requested changes
Seems good, just the 1 enhancement where we don't need the extra div. :)

2020-12-19 19:12 UTC, jancborchardt commented on src/components/Message.vue
> +	<div role="region" :aria-label="t('mail','Message body')">
We don't need an extra div there? The role and aria-label can aimply be added to the existing div. :)

2020-12-19 19:13 UTC, jancborchardt commented
And @yplassiard if you like, check this out and confirm this fixes the issues you reported. Thanks!

2021-01-12 12:05 UTC, jancborchardt approved these changes

2021-01-19 16:05 UTC, merged