Bump devDependencies
nextcloud/mail pull request #4516
Opened 2021-02-12 17:13 UTC by GretaD

Signed-off-by: GretaD <gretadoci@gmail.com>

2021-02-12 17:27 UTC, ChristophWurst requested changes
why do you update all in one btw?

2021-02-12 17:27 UTC, ChristophWurst commented on package.json
> +    "webdav": "^4.0.0"
not a dev dependecy

2021-02-15 08:42 UTC, GretaD commented
> why do you update all in one btw?

not a specific reason. I did it because was only one dependency and the rest dev dependency. Should i keep only the devdep?

2021-02-15 10:30 UTC, ChristophWurst commented
> not a specific reason. I did it because was only one dependency and the rest dev dependency. Should i keep only the devdep?

let's please do the bump separately if possible so we don't accidentally update anything that could cause breakage. also if we have separate bumps then we can bisect the critical update if there are any regressions later :)

2021-02-15 14:47 UTC, GretaD commented
close this and merge the bump individually

2021-02-15 14:47 UTC, closed without merging