Show tags
nextcloud/mail pull request #4894
Opened 2021-04-06 09:24 UTC by GretaD

Signed-off-by: GretaD <gretadoci@gmail.com>

2021-04-09 12:54 UTC, ChristophWurst commented
you can rebase now :)

2021-04-15 11:13 UTC, GretaD commented on src/components/Envelope.vue
> +	border: 1px solid #FFC300;
not the right styling, i did it just to see where my tags are, will fix it

2021-04-15 14:03 UTC, GretaD commented
![taglabel](https://user-images.githubusercontent.com/12728974/114882309-1d167180-9e04-11eb-8d81-9c44e11aea8d.png)

2021-04-16 09:52 UTC, ChristophWurst commented
> The state right now

@nimisha-vijay :eyes: :)

2021-04-28 20:04 UTC, GretaD commented
look at this beauty

![taggin](https://user-images.githubusercontent.com/12728974/116465529-a2bb0800-a86d-11eb-8ffa-b7339818fae1.png)

2021-04-29 09:09 UTC, ma12-co reviewed
Nice one :) 
Just one question, don't you think that those tags are a bit to prominent? Both in terms of size and vibrancy of the colors? 
cc @jancborchardt and @nimisha-vijay

2021-04-29 11:28 UTC, nimisha-vijay commented
This looks so cool! :D I agree that the colours are a tiny bit too intense. Maybe we can do something similar to Deck?
![image](https://user-images.githubusercontent.com/52440189/116543608-af8e3900-a90b-11eb-8501-44ab2f962980.png)

Or have it with a full opacity border but lower opacity fill? (dunno if this is used in any other apps)
![image](https://user-images.githubusercontent.com/52440189/116543492-8f5e7a00-a90b-11eb-9020-d5d5025952a6.png)

What do you guys think? @ma12-co @ChristophWurst @jancborchardt

2021-04-29 12:09 UTC, ma12-co commented
I like deck solution but I also like that in deck the font-size of the tag is smaller than the title. Looking at Greta's screenshot, the tags are much more prominent than sender's name and subject, which is not good. So on top of making colors lighter, I'd shrink them a bit too.

2021-04-29 13:03 UTC, nimisha-vijay commented
Yes correct, decreasing text size sounds good. Maybe also decreasing the padding in the tag by a couple of pixels might make it appear less prominent. 
And maybe align the left of the tags list with the text? So that there is nothing vertically in between the avatars. Does that make sense?

2021-04-29 13:21 UTC, ma12-co commented
> Yes correct, decreasing text size sounds good. Maybe also decreasing the padding in the tag by a couple of pixels might make it appear less prominent.

Agree with reducing padding too!

> And maybe align the left of the tags list with the text? So that there is nothing vertically in between the avatars. Does that make sense?

Not sure about this one, might create a weird empty spot to the right, I'd have to see that in the a list to see how that would work..

2021-04-29 13:25 UTC, ma12-co requested changes

2021-04-29 13:25 UTC, ma12-co commented on src/components/Envelope.vue
> +	border-radius: 35px;
```suggestion
	border-radius: var(--border-radius-pill);
```

2021-04-29 13:25 UTC, ma12-co commented on src/components/Envelope.vue
> +	.tagGroup {
```suggestion
	.tagGroup {
	font-size: calc(var(--default-font-size) * 0.8)
```

2021-05-11 10:32 UTC, GretaD commented
> Or have it with a full opacity border but lower opacity fill? (dunno if this is used in any other apps)
> ![image](https://user-images.githubusercontent.com/52440189/116543492-8f5e7a00-a90b-11eb-9020-d5d5025952a6.png)
> 


@nimisha-vijay what are the codes for these colour? background and border. Jan agreed to have this background, but not border. But i need the border colour to add it to the text.

2021-05-11 11:01 UTC, nimisha-vijay commented
![image](https://user-images.githubusercontent.com/52440189/117804433-675d0800-b275-11eb-940d-3d8973a37ca2.png)

Important: #FF7A66
Todo: #317CCC
Finished: #31CC7C
Personal: #A85BF7
All at 100% opacity for text, 15% for background. 
Later: #DFCC54 at 15% opacity for bg, and #7E6D00 at 100% opacity for text

cc @jancborchardt looks good?

2021-05-12 06:51 UTC, ChristophWurst commented
> Important: #FF7A66
> Todo: #317CCC
> Finished: #31CC7C
> Personal: #A85BF7
> All at 100% opacity for text, 15% for background.
> Later: #DFCC54 at 15% opacity for bg, and #7E6D00 at 100% opacity for text

We can work with some wisely picked defaults for the five *default tags*. But after #4806 the users will be able to assign *any* color to their tags. Will the opacity for text/background work with that?

2021-05-12 07:26 UTC, nimisha-vijay commented
As long as there is enough contrast between text and bg, it should be fine. Lighter colours will probably not work because the text would not be visible (like the yellow tag, later, used a different text and bg colour because otherwise it would not be visible). 
If we are using a colour picker palette, maybe we can explicitly specify values for text and bg colour for each colour in the palette to make sure there are no visiblity/contrast issues?

2021-05-12 18:42 UTC, ChristophWurst commented
> [ <img alt="@GretaD" width="20" height="20" src="https://avatars.githubusercontent.com/u/12728974?s=60&amp;u=cb89ce78f039c123d5a62a1675fadc514afcd51c&amp;v=4"> ](/GretaD)
> ` [fixup! Merge branch 'master' into enhancement/show_tag](/nextcloud/mail/pull/4894/commits/d6e5e5798948a61f6edd23d86da41248ad4d3c1f)`

:warning: is this really a fixup of the *merge*? Please double check. The rebase might drop your changes otherwise.

2021-05-18 15:41 UTC, ChristophWurst requested changes
Making sure we don't merge this lightly

2021-05-18 15:41 UTC, ChristophWurst commented on package.json
> +    "@nextcloud/vue": "^4.0.0-alpha.3",
v4 will pull in `@nextcloud/router` v2 and that will drop some of the browsers that we still support or which are still supported for Nextcloud 20-21

2021-05-18 17:30 UTC, ChristophWurst commented on package.json
> +    "@nextcloud/vue": "^4.0.0-alpha.3",
We decided to drop older browsers.

2021-05-19 11:37 UTC, ChristophWurst commented
- [ ] BUG color indicator should extend to the full height

![Bildschirmfoto von 2021-05-19 13-36-51](https://user-images.githubusercontent.com/1374172/118806391-49ac2600-b8a7-11eb-826e-d120d738dbed.png)

2021-05-19 11:38 UTC, ChristophWurst commented
- [ ] BUG important messages have a large invisible area at which they become clickable. If there is a message blow, you can't select that one

![Bildschirmfoto vom 2021-05-19 13-37-47](https://user-images.githubusercontent.com/1374172/118806561-8710b380-b8a7-11eb-80ca-06720d1b832f.png)

2021-05-20 12:22 UTC, ChristophWurst approved these changes
Works :v:

2021-05-20 12:30 UTC, merged