Fix infinite scroll loading, by removing resizable column support
nextcloud/mail pull request #5258
Opened 2021-06-28 15:45 UTC by ChristophWurst

The infinite scroll loading was broken with https://github.com/nextcloud/mail/pull/5201. This is because the vue-infinite-scroll lib doesn't work when the component of the directive is within a slot, v-if or similar. The reason that `hook:mounted` doesn't fire and therefore no scroll event is ever bound.

I'm intentionally removing resizable columns again to unbreak the scroll feature, as that's way more important and a critical regression. For v1.11.0 we can look into resizable columns again. Either vue-infinite-scoll has to be fixed or we swap out the lib.

Ref https://github.com/ElemeFE/vue-infinite-scroll/issues/77
Ref https://github.com/ElemeFE/vue-infinite-scroll/blob/775b7d386ff4e609eb3360a4ccecee7d9a015c63/src/directive.js#L189

Fixes https://github.com/nextcloud/mail/issues/5234

2021-06-28 15:45 UTC, ChristophWurst commented
/backport to stable1.10

2021-06-29 06:48 UTC, st3iny requested changes
The thread is overlaying the list and needs some form of left margin. Mobile layout looks fine but is missing the left arrow in the top left. I guess we have to add AppDetailsToggle (from nextcloud-vue) manually if we don't use the resizable columns anymore.

![Bildschirmfoto von 2021-06-29 08-43-03](https://user-images.githubusercontent.com/1479486/123749851-287f2200-d8b6-11eb-9687-8188d099c959.png)

2021-06-29 07:41 UTC, ChristophWurst commented
> The thread is overlaying the list and needs some form of left margin.

I don't get that floating thread. What browser is that? Works fine here on FF, both with large window (desktop) and small (mobile)

> missing the left arrow in the top left

Can confirm. I only see the burger menu icon.

> I guess we have to add AppDetailsToggle (from nextcloud-vue) manually if we don't use the resizable columns anymore.

So basically reverting https://github.com/nextcloud/mail/pull/5238 (partly) and https://github.com/nextcloud/mail/pull/5252, right?

2021-06-29 07:57 UTC, st3iny commented
> So basically reverting #5238 (partly) and #5252, right?

Yes. We can't use the upstreamed version of AppDetailsToggle after all because it is not exported.

2021-06-29 09:32 UTC, ChristophWurst commented
I've forked the scroll lib into https://github.com/ChristophWurst/vue-infinite-scroll. Will try to fix the missing hook there and this will be our hack 3 to get the release done :crossed_fingers:

2021-07-01 11:40 UTC, ChristophWurst commented
@GretaD @miaulalala @st3iny please give this one more test :v:

2021-07-01 11:41 UTC, ChristophWurst commented
Wrong PR :see_no_evil:

2021-07-01 11:42 UTC, ChristophWurst commented
Let's continue in https://github.com/nextcloud/mail/pull/5263

2021-07-01 11:42 UTC, closed without merging