Add new message into a modal
nextcloud/mail pull request #5513
Opened 2021-09-08 11:45 UTC by GretaD

fixes #5483 

![newmsgmodal](https://user-images.githubusercontent.com/12728974/132503527-888a4250-924f-4280-81f4-31e5d6ca4a41.png)
Signed-off-by: greta <gretadoci@gmail.com>

2021-09-08 16:37 UTC, ChristophWurst commented on src/components/MailboxThread.vue
>  		<NewMessageDetail v-if="newMessage" />
is `NewMessageDetail` dead now?

2021-09-08 16:46 UTC, st3iny reviewed
- [ ] Looks nice but I found a bug:

1. Open a thread.
2. Click reply.
3. While editing the reply, create a new message.
4. The new modal won't open.

2021-09-08 18:05 UTC, GretaD commented on src/components/MailboxThread.vue
>  		<NewMessageDetail v-if="newMessage" />
no, how dare you?

2021-09-08 18:27 UTC, GretaD commented
> Looks nice but I found a bug:
> 
> 1. Open a thread.
> 2. Click reply.
> 3. While editing the reply, create a new message.
> 4. The new modal won't open.

Did you try to turn it on and off again?

2021-09-22 13:01 UTC, ChristophWurst requested changes
* Let's not make the modal closeable
  + Add a dedicated *Discard draft* button
  + Add a dedicated *Save draft* button
* The route `/apps/mail/box/priority/thread/new` still gives me the old composer, so there is some leftover code to remove, that URL shouldn't exist/work anymore

2021-09-30 10:13 UTC, ChristophWurst commented on src/components/Composer.vue
> +				<button v-if="savingDraft === undefined"
now you see *Discard draft* only when no draft has been saved yet, as soon as there is one the button vanishes, don't you?

2021-10-11 09:20 UTC, jancborchardt commented
@GretaD then I’d say let’s put "Discard draft" into the 3-dot menu. Should be last entry in there, and when clicked, the composer can close automatically. That’s better than the little delete icon :)

2021-10-11 11:17 UTC, GretaD commented
Now it looks like this. Not to confuse people with _**draft saved**_ and _**save draft**_(now this look unnecessary, but we need it) should we rename "save and close draft" instead?

![modalbutton](https://user-images.githubusercontent.com/12728974/136781251-c3046b2f-d639-428a-87c6-8c3bc6d402cb.png)

2021-10-12 09:51 UTC, jancborchardt commented
> Why don't we use a stateful button for saving a draft? When there is no ongoing save it is enabled and has the title "Save draft". If there is a save in progress (either manually or automatically in the background) it is disabled and shows a title like "Saving draft ...".

Sounds good, yep.

2021-10-12 14:12 UTC, GretaD commented
> > Why don't we use a stateful button for saving a draft? When there is no ongoing save it is enabled and has the title "Save draft". If there is a save in progress (either manually or automatically in the background) it is disabled and shows a title like "Saving draft ...".
> 
> Sounds good, yep.

ok, then how do we close the modal after saving? The whole idea of this button is to close the modal after saving. We dont need a save button as a disabled state after we save the draft, because the next step(in the background) is closing the modal. So if i click save, the draft is saved and the modal is closed. @jancborchardt can you please elaborate in steps how should i do it?

2021-11-08 08:22 UTC, ChristophWurst commented
Is it intended that we still open replies at the old editor position instead of the modal?

2021-11-08 08:53 UTC, ChristophWurst commented
- [ ] BUG *Draft saved* stays for second message if previous one was sent

* Open the modal for a new message
* Wait for a draft to be saved
* Send the message
* Click button to composer another message
* *Draft saved* is still shown

It looks like the internal component state is not properly reset.

2021-11-08 08:55 UTC, GretaD commented
> Is it intended that we still open replies at the old editor position instead of the modal?
> 

We didnt discuss anything related to _forward_ or _reply_. The scope of this PR was only Moving _New message_ into a modal. Gmail uses _modal_(whatever is their popup called) only for _New message._

2021-11-08 10:48 UTC, ChristophWurst commented
> > Is it intended that we still open replies at the old editor position instead of the modal?
> 
> We didnt discuss anything related to _forward_ or _reply_. The scope of this PR was only Moving _New message_ into a modal. Gmail uses _modal_(whatever is their popup called) only for _New message._

Okay, fine with me if this is intentional.

2021-11-09 12:08 UTC, ChristophWurst commented on src/components/Composer.vue
> +			this.saveDraftDebounced = debounce(10 * 1000, this.saveDraft)
the function doesn't need to be reset

2021-11-09 13:13 UTC, jancborchardt commented
@GretaD do you have updated screenshots for easier design review? cc @nimishavijay

2021-11-09 13:54 UTC, GretaD commented
> @GretaD do you have updated screenshots for easier design review? cc @nimishavijay

The UI hasnt changed since the last discussion we had. I will update the screenshots when the PR is 100% done, but technically shouldnt have anything to review design wise.

2021-11-11 17:48 UTC, GretaD commented
![newmessagemodal](https://user-images.githubusercontent.com/12728974/141345068-798c48ff-5375-4147-bf3e-111549458161.png)

2021-11-12 15:04 UTC, ChristophWurst commented on src/components/NewMessageDetail.vue
> +				throw new Error('new message details can only be for replies and forwards')
`Error` conflicts with the imported error component

what you want to throw is a new instance of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error

throwing a new constructor instance causes an error

> [Vue warn]: Error in render: "TypeError: _Error__WEBPACK_IMPORTED_MODULE_7__.default is not a constructor"

Import the error component under a different name. then the global javascript `Error` will be unhidden and work as expected.

You can trigger the error if you open `/apps/mail/box/priority/thread/new`

2021-11-12 15:06 UTC, ChristophWurst requested changes
There are still lots of remnant usages of the old *new message* route. Search for `threadId: 'new',`. They all have to be fixed so that the modal opens when we previously triggered this routing.

`mailto:` links and so on are currently broken

2021-11-23 16:56 UTC, st3iny commented on src/components/NewMessageModal.vue
> +	overflow-x: auto;
```suggestion
	overflow-y: auto !important;
	overflow-x: auto !important;
```

Modal isn't scrollable otherwise.

2021-11-24 05:45 UTC, nimishavijay commented
@GretaD would you be posting screenshots when you are done? The previous one you posted looks almost finished already so there wouldn't too much drastic feedback, but just for a final check :)

2021-11-24 11:04 UTC, GretaD commented
> @GretaD would you be posting screenshots when you are done? The previous one you posted looks almost finished already so there wouldn't too much drastic feedback, but just for a final check :)

Yes i will, of course.

2021-11-24 15:23 UTC, GretaD commented
- [ ] Add padding on top of from. (adding more on left and right brings troubles to the borders of from, to cc@nimisha)
- [ ] Remove "Write another message"
- [ ] Add icons on discarded and sent feedback

![discard](https://user-images.githubusercontent.com/12728974/143265560-0fd939f0-1c3f-4081-8188-2adb2d4f8766.png)
![discarddraft](https://user-images.githubusercontent.com/12728974/143265548-a99f509e-75eb-426d-a0f6-3fd11d863f1a.png)
![msgsent](https://user-images.githubusercontent.com/12728974/143265556-09aa8401-b3bb-4934-95c0-2d44239418a2.png)

2021-11-25 06:46 UTC, nimishavijay commented
Looks good! Only 3 minor points about icons
- can we make it bigger (around 44*44 px)
- can we use a lighter colour like `--color-text-maxcontrast`
- for 'Message sent' can we use `icon-checkmark` instead

Ideally it looks similar to this
![image](https://user-images.githubusercontent.com/52440189/143392468-cddc9892-e7f5-486b-880a-415d67fe3575.png)

2021-11-25 10:58 UTC, GretaD commented
![sent](https://user-images.githubusercontent.com/12728974/143429209-4a75fd25-0866-4991-bce1-e5574476621e.png)
![dis](https://user-images.githubusercontent.com/12728974/143429212-964c0d62-6020-40f9-a4ce-895183f38426.png)
![discarddraft](https://user-images.githubusercontent.com/12728974/143429214-0750128a-7939-4739-9504-b272edf4a8e9.png)

2021-12-01 10:27 UTC, ChristophWurst commented
![Bildschirmfoto von 2021-12-01 11-26-28](https://user-images.githubusercontent.com/1374172/144217851-80e0c727-11e2-4680-a173-51d4d185006f.png)

minor design quirk: the modal scrolls when it might not have to

2021-12-01 10:27 UTC, ChristophWurst approved these changes
Works :shipit:

2021-12-01 10:28 UTC, ChristophWurst requested changes

2021-12-01 10:28 UTC, ChristophWurst commented on src/components/AppSettingsMenu.vue
> +			console.debug('MAILTO IS WORKING')
oh nonononono

2021-12-01 10:29 UTC, ChristophWurst requested changes
mailto handling is dead and doesn't open any modal

2021-12-01 10:32 UTC, ChristophWurst commented
- [ ] BUG still tons of remants of the old `new` thread routing that showed the old composer

```
$ rg "'new'" src/
src/components/Envelope.vue
259:                                            threadId: 'new',

src/components/RecipientBubble.vue
175:                                    threadId: 'new',

src/components/Mailbox.vue
152:                                                            threadId: 'new',
244:                                                            threadId: 'new',

src/components/MenuEnvelope.vue
254:                                    threadId: 'new',

src/components/MailboxThread.vue
150:                            this.$route.params.threadId === 'new'

src/views/Home.vue
78:                                     threadId: 'new',
97:                                     threadId: 'new',
```

2021-12-01 10:32 UTC, ChristophWurst commented
- [ ] BUG mailto doesn't work

2021-12-01 10:32 UTC, ChristophWurst commented
- [ ] BUG recipient bubble *Reply* doesn't work

2021-12-01 11:10 UTC, GretaD commented
> mailto handling is dead and doesn't open any modal

this is broken on master for me

2021-12-01 11:12 UTC, GretaD commented on src/components/AppSettingsMenu.vue
> +			console.debug('MAILTO IS WORKING')
im sure you mean nananana

2021-12-01 11:19 UTC, ChristophWurst commented
> this is broken on master for me

Works fine for me with the examples at https://www.rapidtables.com/web/html/mailto.html. `/apps/mail/box/priority/thread/new?to=name%40rapidtables.com` opens the composer and puts in that email address as recipient.

2021-12-01 13:18 UTC, GretaD commented
> * [x]  BUG still tons of remants of the old `new` thread routing that showed the old composer
> 
We removed the ones that are directly connect to _New message_, _edit as new_ and _forward as attachment._ The ones left are for _reply_ and _forward_. The rest will be removed when we fix the reply and forward in a separate PR.

2021-12-01 14:25 UTC, st3iny approved these changes
Tested and works :tada:

2021-12-01 15:54 UTC, merged