Fixes use mailbox.accountId as fallback when accountId isn't defined in Envelope.vue
nextcloud/mail pull request #5748
Opened 2021-11-25 10:07 UTC by StCyr

reported in https://github.com/nextcloud/mail/pull/4288#issuecomment-972831255

Signed-off-by: Cyrille Bollu <cyr.debian@bollu.be>

2021-11-25 10:12 UTC, ChristophWurst requested changes

2021-11-25 10:12 UTC, ChristophWurst commented on src/components/Envelope.vue
> -			const accountId = this.data.accountId ?? this.data.accountId
I don't think the accountId is missing still on envelopes. That was only the case for messages loaded in a paged result. After https://github.com/nextcloud/mail/pull/5601 this shouldn't happen anymore

2021-11-25 15:10 UTC, ChristophWurst commented on src/components/Envelope.vue
> -			const accountId = this.data.accountId ?? this.data.accountId
that is true. it should just be `const accountId = this.data.accountId` :)

2022-03-01 12:38 UTC, GretaD approved these changes
lets get this in

2022-03-01 12:39 UTC, ChristophWurst approved these changes

2022-03-01 12:40 UTC, merged