Migrate template reports to forms
nextcloud/mail pull request #6003
Opened 2022-01-31 15:55 UTC by GretaD

Ref https://github.com/nextcloud/groupware/issues/13

2022-01-31 15:55 UTC, GretaD commented
testing here: https://github.com/GretaD/dummy-repository/blob/main/.github/ISSUE_TEMPLATE/bug_report_mail.yml

2022-01-31 18:17 UTC, ChristophWurst requested changes

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +name: "Bug report: Nextcloud Mail"
use the old title

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +title: "[Bug]: "
drop this line

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +    - type: textarea
`input` should be sufficient

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +    - type: dropdown
I'd use an `input` as we won't curate a list of systems

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +    - type: textarea
`input` is enough

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +    - type: textarea
See https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=. We don't ask for this.

2022-01-31 18:17 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +    - type: textarea
Same. Drop it.

2022-02-01 15:23 UTC, ChristophWurst requested changes

2022-02-01 15:23 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +          label: Database engine version
```suggestion
          label: Database
```

2022-02-01 15:23 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +              _Describe in the "Additional info" section if you chose "Other"._
there is no additional info (yet?)

2022-02-01 15:23 UTC, ChristophWurst commented on .github/ISSUE_TEMPLATE/bug_report_form.yml
> +              - "SQlite"
```suggestion
              - "SQLite"
```

2022-02-03 14:32 UTC, miaulalala commented
Can we add an additional comment field? So people can add more information such as explanations for "Other" configurations for DBs and Servers?

2022-02-03 14:56 UTC, GretaD commented
> Can we add an additional comment field? So people can add more information such as explanations for "Other" configurations for DBs and Servers?

i did, the last push was only for that

2022-02-03 15:08 UTC, miaulalala commented
> > Can we add an additional comment field? So people can add more information such as explanations for "Other" configurations for DBs and Servers?
> 
> i did, the last push was only for that

Didn't see it, mea culpa!

2022-02-04 11:15 UTC, ChristophWurst approved these changes
Drop the old template

2022-02-04 14:44 UTC, GretaD commented
> Drop the old template

Dropped it. Also, please noticed that the section called "Describe the problem" is replaced by "actual behavior" like the old template: https://github.com/GretaD/dummy-repository/blob/main/.github/ISSUE_TEMPLATE/bug_report_mail.yml

2022-02-04 16:24 UTC, ChristophWurst approved these changes
Very clean :broom:

2022-02-04 16:24 UTC, merged