Remove the autocomplete text after selecting recipient
nextcloud/mail pull request #6006
Opened 2022-02-01 15:59 UTC by GretaD

Right now, when you add a recipient and the autocomplete opens, you select a recipient but the text you already added doesnt go away. That means that you should delete the text before adding some other recipient. This pr fixes that

2022-02-02 10:38 UTC, miaulalala requested changes
Auto suggestion selection works great, but I have a few suggestions:

1) there is no way to remove the a reciever that is "in the middle" of the others because deletion only works via backspace. So I would have to delete every entry after the one I want to delete and then reenter them:

Say I want to delete Anna Banana:
![image](https://user-images.githubusercontent.com/7427347/152136837-d00e7a42-d421-4331-8ad1-c48c02c726ca.png)

I have to delete miau_lalala first.

An (x) that removes that entry would be super.

2) Removing an entry with backspace is too easy. A single backspace will remove the entire recipient - possibly make that a double backspace, or make it so the entry is edited instead of removed completely - do so it isn't that easy to remove a recipient accidentally.

3) Google Chrome Autofill keeps messing up the view and takes the focus from the dropdown:

![image](https://user-images.githubusercontent.com/7427347/152137294-6edd5ecb-7354-43ad-9d12-78afaa4d8fd3.png)

`autocomplete="false"` on the input might work if it doesn't break the our autocompletion.

2022-02-02 14:07 UTC, ChristophWurst commented
Legit suggestions @miaulalala. @GretaD if this is achievable with a config flag on the Vue multiselect then go for it. Otherwise I would suggest to offload this to a ticket and address only the non-closing autcomplete in this PR.

2022-02-03 11:10 UTC, GretaD commented
> Legit suggestions @miaulalala. @GretaD if this is achievable with a config flag on the Vue multiselect then go for it. Otherwise I would suggest to offload this to a ticket and address only the non-closing autcomplete in this PR.

Yes, i think the best way would be to change the component and to use EntityPicker instead of changing the Multiselect and adding stuff that EntityPicker already has. 
So, @miaulalala please approve and your suggestions will be included when we do improve the recipients as a whole

2022-02-03 15:05 UTC, miaulalala approved these changes

2022-02-04 12:37 UTC, merged