Migrate composer icons to material design icons
nextcloud/mail pull request #6871
Opened 2022-07-13 10:47 UTC by GretaD

Signed-off-by: greta <gretadoci@gmail.com>

2022-07-13 10:59 UTC, ChristophWurst commented on src/components/Composer.vue
>  						<ActionButton icon="icon-folder" @click="onAddCloudAttachment">
Icon still used

2022-07-13 11:37 UTC, ChristophWurst approved these changes

2022-07-13 11:41 UTC, ChristophWurst requested changes
Why did you rename `button` to `Button`? the nc/vue button component is imported as `VButton`

Are the button changes even necessary for the icon replacement?

2022-07-13 13:19 UTC, GretaD commented
> Why did you rename `button` to `Button`? the nc/vue button component is imported as `VButton`
> 
> Are the button changes even necessary for the icon replacement?

no there are not necessary on this pr because <button> doesnt have an icon. When it has an icon then it needs <Button> I did it here because ive done it with other PRs

2022-07-13 15:09 UTC, ChristophWurst approved these changes
:+1: :elephant:

2022-07-27 12:38 UTC, merged

2022-08-17 08:17 UTC, raimund-schluessler commented
There is quite a bit of chaos with the buttons now, you have `button`, `Button` and `VButton`, whereas they all should be `VButton` (or how you want to import them) regardless of whether they have icons or not. `button` will only render to a standard HTML component and not profit from the accessibility features of the vue component.

`button` (standard HTML button with an icon even):
https://github.com/nextcloud/mail/blob/57ffa52197d78275ce4a94595128b9b85a92bfe7/src/components/Composer.vue#L61-L67

`Button` (probably also standard HTML with an icon):
https://github.com/nextcloud/mail/blob/57ffa52197d78275ce4a94595128b9b85a92bfe7/src/components/Composer.vue#L355-L363

`Button` without icon:
https://github.com/nextcloud/mail/blob/57ffa52197d78275ce4a94595128b9b85a92bfe7/src/components/Composer.vue#L377-L379