Change mail icon to material design icon
nextcloud/mail pull request #6944
Opened 2022-08-01 15:10 UTC by GretaD

to do
change all the mail icons to img folder

2022-08-02 14:25 UTC, jancborchardt commented
All changed to the Material Design icon. While working on it, especially generating out the png versions, I was thinking which files of these are actually still necessary to manually create and which ones are generated by our theming. @juliushaertl do you know, and/or is this documented somewhere in the app dev docs?

2022-08-02 20:33 UTC, juliushaertl commented
> All changed to the Material Design icon. While working on it, especially generating out the png versions, I was thinking which files of these are actually still necessary to manually create and which ones are generated by our theming. @juliushaertl do you know, and/or is this documented somewhere in the app dev docs?

We still need them for cases where ImageMagick is not available or limited. E.g. it is quite common these days to have disable SVG reading by imagemagick in distributions by default, as this may bring additional risk with malicious files.

2022-08-09 17:21 UTC, ChristophWurst commented
Do we even use the icons changed with the latest commit https://github.com/nextcloud/mail/pull/6944/commits/505d682991a4ac55d15bc7750236a76b62a561b6? I think those are unused with your recent changes that dropped all custom icons.

2022-08-12 05:43 UTC, JuliaKirschenheuter reviewed
should all *.svg and *.png be commited / merged?

2022-08-12 06:10 UTC, ChristophWurst approved these changes
Changes look good

2022-08-12 06:11 UTC, ChristophWurst commented on img/LICENSES.md
> +### mail.svg
```suggestion
# Licenses
## mail.svg
```

same for the rest of the doc

2022-08-12 10:00 UTC, GretaD commented
> should all *.svg and *.png be commited / merged?

im not sure if i understand what refer with all, but in other apps we only do the svg, if the png is the same icon.

2022-08-17 02:41 UTC, jancborchardt commented
@ChristophWurst no, they are not used anymore and can be removed. @GretaD you wanted to remove them right?

2022-08-17 07:55 UTC, ChristophWurst approved these changes

2022-08-17 07:55 UTC, ChristophWurst requested changes
Squash

2022-08-17 13:09 UTC, ChristophWurst approved these changes

2022-08-18 08:32 UTC, merged