Change the 'show image' styling
nextcloud/mail pull request #6947
Opened 2022-08-02 13:31 UTC by GretaD

this is how i tried to make it work with the state of actions we have now.
But i agree with Marco's comment here: https://github.com/nextcloud/mail/issues/6122#issuecomment-1202480324

2022-08-02 13:37 UTC, GretaD commented
@jancborchardt and @nimishavijay please have a look at this solution and if you're ok with it

2022-08-02 14:23 UTC, jancborchardt requested changes
- [x] "Show image" → "Show images"
- [x] The eye icon is not necessary, as per mockup
- [x] In the menu, the icons are all the same, so either we should go with no icons or:
    - Temporarily: https://fonts.google.com/icons?selected=Material%20Icons%3Aimage%3A
    - Show from this email: https://fonts.google.com/icons?selected=Material%20Icons%3Amail%3A
    - Show from this domain: https://fonts.google.com/icons?selected=Material%20Icons%3Adomain%3A
    
Regarding the comment from @marcoambrosini, either is fine with me. Indeed using the tertiary button component would be more accurate since it’s not a link which goes somewhere.

2022-08-02 16:33 UTC, GretaD commented
> * [ ]  "Show image" → "Show images"
> * [ ]  The eye icon is not necessary, as per mockup
> * [ ]  In the menu, the icons are all the same, so either we should go with no icons or:
>   
>   * Temporarily: https://fonts.google.com/icons?selected=Material%20Icons%3Aimage%3A
>   * Show from this email: https://fonts.google.com/icons?selected=Material%20Icons%3Amail%3A
>   * Show from this domain: https://fonts.google.com/icons?selected=Material%20Icons%3Adomain%3A
> 
> Regarding the comment from @marcoambrosini, either is fine with me. Indeed using the tertiary button component would be more accurate since it’s not a link which goes somewhere.

all the point can be delivered but the icon one. The action must have an icon, sorry should have commented that before. If we wait for the vue changes, this will be delivered a bit late, if we move on with my solution, i will look like this(and your comments, but with an icon)

2022-08-02 18:22 UTC, jancborchardt commented
@GretaD cool, and fine for now with the icon too, but then also use the "image" filetype icon instead of "eye".

2022-08-03 06:24 UTC, marcoambrosini commented
We can definitely add the option not to have an icon and have the menus triggered by tex-tonly buttons. I think it totally makes sense.

2022-08-03 06:25 UTC, marcoambrosini commented
...and that will automatically be the case when https://github.com/nextcloud/nextcloud-vue/issues/2768 happens

2022-08-03 07:43 UTC, GretaD commented
> We can definitely add the option not to have an icon and have the menus triggered by tex-tonly buttons. I think it totally makes sense.

i know that, but when it is going to be released? :)

2022-08-08 09:45 UTC, marcoambrosini commented
pr is there https://github.com/nextcloud/nextcloud-vue/pull/2911#issuecomment-1207891395
Let's wait for more reviewers since it's a big change. Also you can review @GretaD :) 

Once that's we can do a minor release

2022-08-16 14:06 UTC, ChristophWurst commented
How is this unblocked when it depends on https://github.com/nextcloud/nextcloud-vue/pull/2911 and this app still uses v5?

2022-08-16 14:29 UTC, GretaD commented
> How is this unblocked when it depends on [nextcloud/nextcloud-vue#2911](https://github.com/nextcloud/nextcloud-vue/pull/2911) and this app still uses v5?

ah sorry didnt see you added the component on desc. I am not using that component, that was not related to actions without icons, what Marco meant(double checked with him) is that after that is in, we can edit the actions on vue again and add a slot with no icons. 

What i did was hiding the icon with display none. 
I dont have time to spend on the component now, so we can either do this or wait till we have time.

2022-08-17 02:39 UTC, jancborchardt requested changes
Except changing it to plural it looks good to me :)

2022-08-17 02:39 UTC, jancborchardt commented on src/components/MessageHTMLBody.vue
> +			<Actions type="tertiary" :menu-title="t('mail', 'Show image')">
```suggestion
			<Actions type="tertiary" :menu-title="t('mail', 'Show images')">
```

2022-08-17 14:07 UTC, GretaD commented
not ready to merge

2022-08-17 14:12 UTC, GretaD commented
> not ready to merge

ready now, please reviewers test it

2022-08-17 14:16 UTC, ChristophWurst approved these changes
Tested, works

2022-08-18 06:35 UTC, merged