Migrate icons to material design icons
nextcloud/mail pull request #6995
Opened 2022-08-12 13:48 UTC by GretaD

wip

2022-08-16 12:06 UTC, GretaD commented on src/components/MessageAttachments.vue
> +	margin-inline-start: 170px;
this is not what we want, will change it asap

2022-08-16 13:37 UTC, st3iny requested changes
I discovered multiple issues while testing.

**NOTE:** Some of those issues might be on main too or caused by the nc-vue upgrade to 6.0.0.

## 1. Send later ActionButtons are jumping on hover
[Peek 2022-08-16 15-20.webm](https://user-images.githubusercontent.com/1479486/184892220-60cf5769-0f06-4269-9c71-607346b92c77.webm)

## 2. Attachment modal can't be interacted with and closed

(I'm spamming left click as I hover various elements in the video.)

[Peek 2022-08-16 15-29.webm](https://user-images.githubusercontent.com/1479486/184892588-36f22da8-2ea4-4538-a5b7-428cbe241a4e.webm)

The close button is not working which resulted in me being stuck and having to force reload the page.

![ksnip_20220816-152733](https://user-images.githubusercontent.com/1479486/184893107-95d24611-af1c-4e23-8003-0c24608cf35e.png)

## 3. Account settings modal can't be closed via the `X`

However, it can be closed by clicking outside.

![ksnip_20220816-152501](https://user-images.githubusercontent.com/1479486/184892886-9d2ab906-1185-418f-b4d7-3fb68b3a832c.png)

## 4. The account creation modal is missing its form

![ksnip_20220816-153114](https://user-images.githubusercontent.com/1479486/184893214-9c2a11e2-6787-45e6-bd18-600146c79ab4.png)

2022-08-23 12:57 UTC, GretaD commented
the problems Richard found are fixed. This pr https://github.com/nextcloud/mail/pull/7060 is needed to move on

2022-08-23 18:12 UTC, ChristophWurst approved these changes

2022-08-26 12:43 UTC, merged