Reroute to priority mailbox when a mailbox is deleted
nextcloud/mail pull request #7448
Opened 2022-10-18 12:25 UTC by GretaD

fixes #7406

2022-10-18 12:48 UTC, ChristophWurst requested changes

2022-10-18 12:48 UTC, ChristophWurst commented on src/components/NavigationMailbox.vue
> +								this.$router.push({
the reroute should only happen if the *current mailbox* is deleted

2022-10-18 12:48 UTC, JuliaKirschenheuter approved these changes
looks good, but haven't tested

2022-10-18 17:36 UTC, ChristophWurst requested changes

2022-10-18 17:36 UTC, ChristophWurst commented on src/components/NavigationMailbox.vue
> +								if (this.$route.params.mailboxId) {
```suggestion
								if (this.$route.params.mailboxId == this.mailbox.databaseId) {
```

2022-10-19 06:12 UTC, ChristophWurst requested changes

2022-10-19 06:12 UTC, ChristophWurst commented on src/components/NavigationMailbox.vue
> +								if (this.$route.params.mailboxId === this.mailbox.databaseId) {
This can never be truthy. `this.$route.params.mailboxId` is a string, `this.mailbox.databaseId` is a Number.

2022-12-14 16:05 UTC, ChristophWurst commented on src/components/NavigationMailbox.vue
> +								if (this.$route.params.mailboxId === this.mailbox.databaseId) {
It is an int before the page load. After a page load it becomes a string.

2022-12-20 18:13 UTC, ChristophWurst commented
@GretaD give this a final test but I think this is mergeable now

2022-12-21 07:20 UTC, ChristophWurst approved these changes

2022-12-21 07:20 UTC, merged