Add search box for outbox and PI
nextcloud/mail pull request #7461
Opened 2022-10-19 15:35 UTC by GretaD

2022-10-20 07:59 UTC, GretaD commented
cc @sazanof its still a draft but just so you are aware :)

2022-10-21 13:27 UTC, ChristophWurst commented
> Fixes #7461

Wrong ticket?

2022-10-21 18:51 UTC, sazanof requested changes
@GretaD super cool!

How do you think, may be also edit styles in SearchMessages.vue in this PR too?

```
.search-messages {
	min-height: 52px;
	margin: 3px 0 0 52px;
	border-right: 1px solid var(--color-border);
	position: relative;
	display:flex;
	align-items: center;
```
![image](https://user-images.githubusercontent.com/3595562/197268634-d2d57d2c-15cb-49ee-b7bb-4f636b4ca619.png)

2022-11-01 13:34 UTC, sazanof approved these changes
Tested and works! Nice =)

___________________

As for the "Outbox" filter, it is difficult to implement it from what is. Outgoing messages use a local table in the database, with a different structure. 
So we need to do a separate search for them.

In addition, under normal circumstances, this folder should be empty.

2022-11-01 14:08 UTC, GretaD commented
> In addition, under normal circumstances, this folder should be empty.

exactly, or with a little number of emails that can be easily found, thus no need for a search field, at least for now.

2022-11-01 15:28 UTC, st3iny approved these changes
Tested and works.

2022-11-01 15:30 UTC, st3iny commented on src/components/Outbox.vue
>  		</div>
To fix an ESLint issue.

2022-11-01 15:54 UTC, merged