Improve loading experience for message on thread
nextcloud/mail pull request #7562
Opened 2022-11-09 16:30 UTC by GretaD

Signed-off-by: greta <gretadoci@gmail.com>

2022-11-11 11:04 UTC, GretaD commented
https://user-images.githubusercontent.com/12728974/201327212-76c95f9b-1989-428d-8b7c-94119c7086f0.mp4

2022-11-11 15:02 UTC, ChristophWurst commented on src/components/ThreadEnvelope.vue
> +		min-height: 150px;
this doesn't seem to work. the message to iframe loader still causes a jump

2022-11-14 16:21 UTC, GretaD commented
the loading starts at sec 16
i cannot see a jump with any thread im testing
[Screencast from 14.11.2022 17:19:42.webm](https://user-images.githubusercontent.com/12728974/201711485-cd00060c-376f-49d1-b4a7-92d5b87799f3.webm)

2022-11-14 17:15 UTC, GretaD commented
![Bildschirmfoto vom 2022-11-14 17-33-34](https://user-images.githubusercontent.com/1374172/201714509-2b308b98-d58f-4dbd-89fc-f7e5b5ad0484.png)

ahh, but thats the second icon(before the iframe loads) that i havent removed yet. You proposed to do it 3 prs and this is the second one. On this pr's description i added that this pr does.

2022-11-14 17:17 UTC, ChristophWurst approved these changes
:+1: :elephant:

2022-11-14 23:33 UTC, jancborchardt commented
Next to the jumping loading icon, 2 other things (possibly for other PRs, your call):
- The "Loading thread" message in the beginning is not needed, just show the loading thread directly
- The height of the container is still very small. Only mails which are just 1 sentence or word long will fit in there. So the default message container height (when the loading spinner is shown) can be increased. E.g. let's say that a mail with 5-7 lines of text could fit.

2022-11-14 23:34 UTC, jancborchardt requested changes
Next to the jumping loading icon, 2 other things (possibly for other PRs, your call):
- [ ] The "Loading thread" message in the beginning is not needed, just show the loading thread directly
- [ ] The height of the container is still very small. Only mails which are just 1 sentence or word long will fit in there. So the default message container height (when the loading spinner is shown) can be increased. E.g. let's say that a mail with 5-7 lines of text could fit.

2022-11-16 15:04 UTC, GretaD commented
Superseded by #7615

2022-11-16 15:04 UTC, closed without merging