Replace vue-clipboard2 with navigation.clipboard api
nextcloud/mail pull request #7602
Opened 2022-11-15 14:21 UTC by kesselb

2022-11-16 16:38 UTC, st3iny approved these changes

2022-11-16 16:38 UTC, st3iny requested changes

2022-11-18 16:28 UTC, kesselb commented on src/components/RecipientBubble.vue
> +import '@nextcloud/dialogs/dist/index.css'
Thanks :see_no_evil:

2022-12-07 22:11 UTC, st3iny approved these changes

2022-12-07 22:11 UTC, merged