Handle error when thread id is unknown
nextcloud/mail pull request #7617
Opened 2022-11-16 17:09 UTC by GretaD

fixes #7608 

- [x] needs #7643

2022-11-16 17:52 UTC, ChristophWurst requested changes

2022-11-16 17:52 UTC, ChristophWurst commented on src/components/Thread.vue
> +					showError(t('mail', 'Could not load your message thread, it doesnt exist or is deleted'))
```suggestion
					showError(t('mail', 'Could not load your message thread because it doesn't exist or has been deleted'))
```

2022-11-16 17:52 UTC, ChristophWurst commented on src/components/Thread.vue
>  				}
add an `else` for any other error and show *Could not load your message thread*

that could happen if the network is down, etc.

2022-11-17 09:37 UTC, ChristophWurst reviewed
Why did you go for `showError` instead of `this.errorMessage`?

Your toast will be temporary and the loading is still infinite, isn't it?

2022-11-17 09:53 UTC, GretaD commented
> Why did you go for `showError` instead of `this.errorMessage`?
> 
> Your toast will be temporary ~and the loading is still infinite, isn't it?~ loading stops.

Just so i could have a feedback on the UI which is the toast.

2022-11-17 09:58 UTC, ChristophWurst commented
You are right. `errorMessage` is no longer used in the template. Let me see why.

2022-11-17 10:14 UTC, ChristophWurst commented
> Let me see why.

It was the usual suspects: https://github.com/nextcloud/mail/pull/3540

2022-11-17 10:16 UTC, ChristophWurst commented
Can we revive the old error empty content to show instead of the loading view when the thread can't be loaded? This makes the error show in place and permanent. Toasts vanish.

2022-11-17 11:00 UTC, GretaD commented
yes, done. Theres only one problem. I cannot click an envelope now, i can scroll and click mailboxes but not envelopes.

![Screenshot from 2022-11-17 11-58-22](https://user-images.githubusercontent.com/12728974/202428915-8a8d709a-e14a-4de5-b40c-4d5c6c5e62f4.png)

2022-11-17 11:37 UTC, ChristophWurst commented
I think Vue recycles the `Thread` component. The component has no input props but relies on the *route*. See the `$route` watcher. It calls `resetThread` for every route change. Reset `this.error` and `this.errorMessage` in that method.

2022-11-21 11:46 UTC, GretaD commented
after resetting `this.error ` and  `this.errorMessage` the envelope list is not responsive anymore

2022-11-21 11:53 UTC, ChristophWurst commented
It is repsonsive but the custom .emtpycontent div of the error overlaps the list. Use your browser inspection on top of the evenlope list. 
![Bildschirmfoto vom 2022-11-17 18-21-03](https://user-images.githubusercontent.com/1374172/203045572-50696aec-cd0c-401d-a20e-998a9ef1ff07.png)

2022-11-22 14:36 UTC, GretaD commented
> after resetting `this.error ` and `this.errorMessage` the envelope list is not responsive anymore

now it is :)

2022-11-22 16:13 UTC, ChristophWurst reviewed
Less technical, more human

2022-11-22 16:13 UTC, ChristophWurst commented on src/components/Thread.vue
>  					this.error = error
```suggestion
					this.error = t('mail', 'Could not load your message thread')
					this.errorMessage = t('mail', 'The thread doesn\'t exist or has been deleted')
```

2022-11-22 18:05 UTC, GretaD commented on src/components/Thread.vue
>  					this.error = error
:robot:

2022-11-23 16:00 UTC, ChristophWurst approved these changes
An icon would make it perfect

2022-11-23 19:05 UTC, merged