chore(autoloading): Only use authoritative classmaps for production
nextcloud/mail pull request #8020
Opened 2023-02-14 10:51 UTC by ChristophWurst

## How to test

1) Run `composer i`
2) Check `vendor/composer/autoload_real.php`

Main: you find a `$loader->setClassMapAuthoritative(true);` and switching between branches could potentially trigger missing classes if you don't run `composer i` or `composer dump-autoload` to update the class map
Here: class map is still optimized on dev but tries to look up missing classes. On production we use the authoritative classmaps nevertheless.

2023-02-14 12:41 UTC, miaulalala requested changes
I tried testing this with the following steps:

1) Check out main
2) Run composer i
3) check out this branch
4) create new empty migration via occ and bump info.xml
5) run the upgrade from the web ui

Unfortunately the lookup didn't work with the typical error that happens when the composer autoloader wasn't dumped:

![image](https://user-images.githubusercontent.com/7427347/218741058-6e3f8513-ffc9-4fc5-9e34-6c4f02784e0c.png)

2023-02-16 09:37 UTC, st3iny approved these changes
Tested and works.

---

@miaulalala The existing autoloader has the authoritative state ingrained and thus it has to be generated once more after this PR. The setting from `composer.json` is only read on dumping the autoloader (or installing dependencies).

`vendor/composer/autoload_real.php`
```
  41   │         }
  42   │
  43   │         $loader->setClassMapAuthoritative(true);
  44   │         $loader->register(true);
  45   │
  46   │         if ($useStaticLoader) {
```

2023-02-16 09:43 UTC, ChristophWurst commented
Excellent catch. That explains the missing class despite my changes.

2023-02-17 09:42 UTC, miaulalala approved these changes
Tested again:

1) Checked out the PR
2) composer i
3) created migration
4) bumped info.xml
5) started upgrade via webUI
6) Migration runs through
7) Profit!

2023-02-17 09:44 UTC, merged