Fix missing mailboxes on new account
nextcloud/mail pull request #8156
Opened 2023-02-27 20:17 UTC by hamza221

fixes #8041

2023-02-28 15:20 UTC, ChristophWurst commented on lib/Controller/AccountsController.php
> +			$this->mailboxSync->sync($account, $this->logger);
suggestion: add try-catch and carry on regardless of errors. mailbox sync should not block the creation of an account

2023-03-01 13:58 UTC, ChristophWurst requested changes

2023-03-01 13:58 UTC, ChristophWurst commented on lib/Controller/AccountsController.php
> +			$this->logger->error('Failed syncing the newly created accoutnt' . $e->getMessage(), [
typo

2023-03-01 13:59 UTC, ChristophWurst commented
To ease incremental reviews please fixup+push instead of amend+force-push until approval and green CI

2023-03-01 14:21 UTC, ChristophWurst approved these changes

2023-03-01 16:51 UTC, hamza221 commented
Should we ignore codecov?

2023-03-01 18:41 UTC, merged