Change certificate icon to a lock one
nextcloud/mail pull request #8174
Opened 2023-03-01 21:21 UTC by GretaD

fixes #8085

2023-03-01 21:45 UTC, hamza221 commented
This won't be needed after #8175 gets merged

2023-03-02 07:35 UTC, ChristophWurst requested changes

2023-03-02 07:35 UTC, ChristophWurst commented on src/components/AliasForm.vue
> +import IconCertificate from 'vue-material-design-icons/Lock'
```suggestion
import IconLock from 'vue-material-design-icons/Lock'
```

2023-04-03 15:43 UTC, GretaD commented
this is ready to go if we decide to keep this PR

2023-04-03 18:24 UTC, hamza221 commented
#8175 is also done, so I think we can close this, @ChristophWurst  what do you think?

2023-04-04 12:21 UTC, closed without merging