chore(CI): Adjust testing matrix for Nextcloud 26 on stable3.0
nextcloud/mail pull request #8198
Opened 2023-03-03 11:51 UTC by GretaD

2023-03-03 11:52 UTC, ChristophWurst requested changes
master is 27 and doesn't work. Mail stable3.0 can only test against server stable26

2023-03-03 11:52 UTC, ChristophWurst commented on .github/workflows/test.yml
> +        nextcloud-versions: ['master', 'stable26']
```suggestion
        nextcloud-versions: ['stable26']
```

2023-03-03 14:10 UTC, ChristophWurst approved these changes

2023-03-03 14:11 UTC, ChristophWurst requested changes

2023-03-03 14:11 UTC, ChristophWurst commented on .github/workflows/test.yml
> +        nextcloud-versions: ['stable26']
there are two more usages of `master` in this workflow file

2023-03-03 14:12 UTC, ChristophWurst commented
psalm worlkflow should also switch to dev-stable26

2023-03-03 15:58 UTC, ChristophWurst approved these changes

2023-03-06 09:21 UTC, st3iny approved these changes

2023-03-06 09:29 UTC, merged