Show message timestamp in action menu
nextcloud/mail pull request #8294
Opened 2023-03-23 21:23 UTC by hamza221

closes #8267
![image](https://user-images.githubusercontent.com/40746210/227366029-2446643f-0935-4449-90ab-6b1b36b6f7cb.png)

2023-03-24 08:43 UTC, ChristophWurst reviewed
Awesome! Let's wait for the approval of the designers

2023-03-24 08:43 UTC, ChristophWurst commented on src/components/Envelope.vue
> +		messageLongDate() {
make this a computed prop

2023-04-05 09:34 UTC, nimishavijay requested changes
Looks good! One suggestion: add a [clock icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aschedule%3A) on the left of the item so that all the text is nicely aligned :)

2023-04-11 06:51 UTC, ChristophWurst commented on src/util/shortRelativeDatetime.js
> +	return moment(date * 1000).format(('MMMM D, YYYY H:mm'))
this is a tricky topic. I think the format should depend on the user's locale. Let's go with the format `lll`. See https://momentjs.com/ for examples.

2023-04-11 16:12 UTC, nimishavijay approved these changes
Nice! 🚀

2023-04-18 07:39 UTC, merged