fix(Snooze): Sort snooze mailbox as specialUse
nextcloud/mail pull request #8774
Opened 2023-08-18 09:50 UTC by JohannesGGE

If a dedicated snooze mailbox is selected in the account settings, it is shown as a special use mailbox before none special mailboxes

|before|after|
|---|---|
|![image](https://github.com/nextcloud/mail/assets/74607597/6332e6f8-376b-4bc3-9334-5da745d8c71e)|![image](https://github.com/nextcloud/mail/assets/74607597/7e2ab719-39b9-4082-815c-572815a0688d)|

2023-08-18 11:06 UTC, hamza221 approved these changes

2023-08-18 11:22 UTC, st3iny approved these changes
Didn't test but looks good.

2023-08-18 11:23 UTC, st3iny requested changes
Frontend tests are failing :eyes:

2023-08-21 06:14 UTC, st3iny approved these changes

2023-08-21 06:14 UTC, merged