[Feature] #9298 : Add several e-mail addresses into address fields at once
nextcloud/mail pull request #9347
Opened 2024-02-15 20:14 UTC by arublov

* Resolves #9298

2024-02-16 12:55 UTC, arublov commented
@ChristophWurst I pushed this last commit into this PR for review, and I'm not sure if it applies to this task or not:

1. try to add something like this: "Test Test <test@test.com>, Test Test1 <a@rublov.me>" I need to compare and then do something?
2. If this is the string: "Test Test Test <test@test.com>/ Test Test Test1 <a@rublov.me>" it's wrong and do I need to do something?

Hint this is relevant to this task, if yes, I will cover these cases with code. If there are more, I will be ready to solve them :)

2024-02-21 13:42 UTC, arublov commented
@ChristophWurst any updates here? Thanks :)

2024-02-23 16:51 UTC, arublov commented
@ChristophWurst , yes done, I fixed some cases and tested, could you please see the new changes and write me feedback, what do you think about this? Maybe I need to change something in my solution?

P.S. Maybe need to move the regex to another space somewhere, so that it can be accessed in any other classes in the project?

2024-02-23 17:05 UTC, arublov commented
@ChristophWurst I was doing research on this a couple days ago and tried your examples based on thunderbird, gmail and roundcube. So created a more flexible solution based on these apps and my research, so if I need to further improve or change the logic in my solution I will be happy to work on this further :)

### **Just FYI:** 

### How works Thunderbird: 
1. When string = "Jane Doe, MSc jane@doe.tld; Jane Doe, MSc jane@doe.tld" :
<img width="689" alt="Screenshot 2024-02-21 at 3 05 57 PM" src="https://github.com/nextcloud/mail/assets/39839367/8b307229-49ee-4d65-bede-0c97cf289c48">

2. When string = "Jane Doe, MSc jane@doe.tld"  :
<img width="598" alt="Screenshot 2024-02-21 at 3 33 15 PM" src="https://github.com/nextcloud/mail/assets/39839367/c37324e5-55ea-4751-be8c-08d8239bdb57">


### How works Web Gmail 
1. When string = "Jane Doe, MSc jane@doe.tld; Jane Doe, MSc jane@doe.tld" :
<img width="598" alt="Screenshot 2024-02-21 at 3 14 00 PM" src="https://github.com/nextcloud/mail/assets/39839367/78bc69f2-0f90-432e-981d-99fca9bcddd2">

2. When `string = "Jane Doe, MSc jane@doe.tld`" :
<img width="598" alt="Screenshot 2024-02-21 at 3 33 38 PM" src="https://github.com/nextcloud/mail/assets/39839367/bbb9b994-360b-4a36-9eb2-158a4c4f71b7">

All of these invalid 

_Look: [rfc822 standard](https://www.w3.org/Protocols/rfc822/#z10)_

2025-09-09 19:12 UTC, 4liceD commented
Is this PR still being worked on? I just found out about it and honestly was surprised that nextcloud doesn't support pasting multiple addresses yet.

2025-10-15 13:07 UTC, Ephtolens commented
Hi ! 
I'm finding out this PR after trying to put multiple email at once. What's the next step ? Is there a way we can help this PR to succeed ?
Thanks

2026-02-25 13:26 UTC, Muffexx commented
I think this feature should get some attention.

As a workaround, I started creating mailto links from my lists of email addresses. This way the email addresses are inserted properly.

2026-02-25 13:36 UTC, ChristophWurst commented
Rebased to resolve conflicts

2026-02-25 13:40 UTC, ChristophWurst requested changes
1. Bug: parseEmailList uses space as delimiter but this breaks "Display Name" labels                                                                                                                                                         
  2. Bug: option.email may be undefined
  3. getLabelAndAddress regex is case-sensitive
  4. getLabelAndAddress returns false instead of a consistent type
  5. saveDraftDebounced() is called per-address in pushNewAddr
  6. No tests
  7. The regex in getLabelAndAddress has a suspicious trailing group

I'll try to fix these.

2026-02-25 18:20 UTC, kesselb commented on src/util/emailAddress.js
> +	let start = 0
We added https://www.npmjs.com/package/address-rfc2822 recently. 
Could you try to reuse their parser?

2026-02-25 18:25 UTC, ChristophWurst commented on src/util/emailAddress.js
> +	let start = 0
Yes, will definitely try!

2026-05-13 10:39 UTC, ChristophWurst commented
@coderabbitai review

2026-05-19 07:49 UTC, ChristophWurst commented
@coderabbitai review

2026-05-19 07:51 UTC, ChristophWurst commented
This works well now. If there are no major issues found we can merge it.

2026-05-19 11:58 UTC, ChristophWurst approved these changes
Tested, cleaned-up and works 👍

2026-05-19 12:27 UTC, merged