Enh: Improve smart replies prompt
nextcloud/mail pull request #9426
Opened 2024-02-29 14:29 UTC by hamza221

2024-03-06 18:32 UTC, ChristophWurst reviewed
Makes sense

2024-03-06 18:32 UTC, ChristophWurst commented on lib/Service/AiIntegrations/AiIntegrationsService.php
> +			return json_decode($replies, true);
open the code with phpstorm and let it fix the json_decode to throw on error ;-)

2024-03-06 18:32 UTC, ChristophWurst commented on lib/Service/AiIntegrations/AiIntegrationsService.php
> +			return json_decode($replies, true);
and don't cache if you can't decode the replies. else the same decoding error happens again and again.

2024-06-11 18:23 UTC, st3iny requested changes

2024-06-11 18:23 UTC, st3iny commented on lib/Controller/MessagesController.php
> +			$replies = array_values($this->aiIntegrationService->getSmartReply($account, $mailbox, $message, $this->currentUserId));
Breaks if the method returns null when the reply of the LLM could not be parsed. Need to check if the result of `getSmartReply()` is null before passing it to `array_values()`.

`array_values(): Argument #1 ($array) must be of type array, null given in file '/home/richard/src/nextcloud/master/dev_apps/mail/lib/Controller/MessagesController.php' line 911`

2024-06-11 18:24 UTC, st3iny commented
I'm sorry for the late review :see_no_evil:

2024-06-12 12:41 UTC, st3iny reviewed
Tested and works.

2024-06-12 12:41 UTC, st3iny approved these changes

2024-06-12 13:22 UTC, merged